image: maven:3.8.4-openjdk-17

pipelines:
  default:
    - step:
        name: Snyk Security Scan
        script:
          - apt-get update && apt-get install -y curl unzip
          - curl -Lo snyk "https://github.com/snyk/snyk/releases/latest/download/snyk-linux"
          - chmod +x snyk
          - mv snyk /usr/local/bin/
          - snyk auth $SNYK_TOKEN
          - snyk test --all-projects || exit 1  # Fails pipeline if vulnerabilities are found

    - step:
        name: Build and Test
        caches:
          - maven
        script:
          - mvn clean install