pipeline {
    agent any
    
    stages {
        stage("Code Cloning") {
            steps {
                echo "Cloning repository.git.."
                git url: "https://github.com/Enigmaacs/adya-django-notes-app.git", branch: "main"
            }
        }
        stage("Build") {
            steps { 
                echo "Building the image..."
                sh "docker build -t notes-app:latest ."
            }
        }
        stage("Pushing image to Dockerhub") {
            steps {
                echo "Pushing image to DockerHub..."
                withCredentials([usernamePassword(credentialsId: 'dockerHub', passwordVariable: 'dockerHubPass', usernameVariable: 'dockerHubUser')]) {
                    sh "docker image tag notes-app:latest ${dockerHubUser}/notes-app:latest"
                    sh "docker login -u ${dockerHubUser} -p ${dockerHubPass}"
                    sh "docker push ${dockerHubUser}/notes-app:latest"
                }
            }
        }
        stage("Deploy") {
            steps {
                echo "Deploying the container..."
                sh "docker run -d -p 8000:8000 sushmaskillmine/notes-app:latest"
            }
        }
    }
}
